kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: result
  labels:
    app: voting-app
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: result
          image: mgrillet/result:latest
