kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: vote
  labels:
    app: voting-app
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: quay.apps.lz-np2.ent-ocp4-useast1.aws.internal.das/an222685ad/vote:latest
