kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: worker
  labels:
    app: voting-app
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: worker
          image: mgrillet/worker:latest
