kind: Secret
apiVersion: v1
metadata:
  name: db
  labels:
    template: postgresql-ephemeral-template
data:
  database-name: cG9zdGdyZXM=
  database-password: cG9zdGdyZXM=
  database-user: cG9zdGdyZXM=
type: Opaque
