kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: result-s2i
  labels:
    app: voting-app
spec:
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: centos/nodejs-10-centos7
    type: Source
  source:
    type: Git
    git:
      uri: "https://github.com/Treeptik/openshift-voting-app.git"
      ref: master
    contextDir: voting-app/result/src
  output:
    to:
      kind: ImageStreamTag
      name: result:latest