kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: worker-s2i
  labels:
    app: voting-app
spec:
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: fabric8/s2i-java:3.1-java8
  source:
    type: Git
    git:
      uri: "https://github.com/Treeptik/openshift-voting-app.git"
      ref: master
    contextDir: voting-app/worker/src
  output:
    to:
      kind: ImageStreamTag
      name: worker:latest